[package]
name = "reversi-gui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.14.0"
reversi-core = { path = "../core" }
reversi-com = { path = "../com" }
rand = "0.8.4"
