[package]
name = "reversi-dump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.6"
reversi-core = { path = "../core" }
reversi-com = { path = "../com" }
